CREATE TABLE STAFF_DETAILS ( STAFF_ID VARCHAR(7) PRIMARY KEY,
                         FIRST_NAME VARCHAR(10) NOT NULL,
								  LAST_NAME VARCHAR(15) NOT NULL,
								 AADHAR_NUMBER varchar(12) NOT NULL,
								 GENDER varchar(8) NOT NULL,
								 EMAIL_ID varchar(25) NOT NULL,
								 PHONE_NUMBER varchar(10) NOT NULL,
								 PASSWORD_ VARCHAR(15) NOT NULL);