CREATE TABLE CAR_SEDAN ( CAR_ID VARCHAR(7) PRIMARY KEY,
                         CAR_NO VARCHAR(10) NOT NULL,
								 CAR_NAME VARCHAR(15) NOT NULL,
								 MILAGE DECIMAL(5,2) NOT NULL,
								 ENGINE_CAP VARCHAR(10) NOT NULL,
								 PRICE DECIMAL(12,2) NOT NULL,
								 YEAR_MNFCTRE DATE NOT NULL,
								 STAT_US VARCHAR(50) NOT NULL,
								 CAR_RENTAL_RATE DECIMAL(7,2) NOT NULL);